name = "Diffy's Maodded Minecraft"
author = "Diffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8e5acc290cdc9e78e7a32db7c86488a1cf184144a6349dcdc35fcf15785d8a7"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
