name = "Diffy's Maodded Minecraft"
author = "Diffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b162c20f9766d72ea2ddb30111885af86fb3058832f7579d7b5e32a275ce28ee"

[versions]
fabric = "0.16.12"
minecraft = "1.21.1"
