name = "Maodded Minecraft"
author = "Diffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17ebdd77d2d632031c67d5b30cba8e9e8a1f800288937d59a45d1b8af51afc31"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
