name = "Maodded Minecraft"
author = "Diffy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "265798c830f6887dc52a6aaca27a41f2ed3510c339ae37709df4b78cb834da2f"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
